name: Bump develop version
on:
  push:
    branches: 
      - 'develop'
      - '!release'
jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.ACTION_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          branch: develop
          github_token: ${{ secrets.ACTION_TOKEN }}
          changelog: ''
