name: Bump release version
on:
  push:
    branches: releases
jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.ACTION_TOKEN }}"
          fetch-depth: 0
      
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          branch: develop
          github_token: ${{ secrets.ACTION_TOKEN }}
          changelog: ''

      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: "configs/configuration_repo.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Create Release
        uses: softprops/action-gh-release@6034af24fba4e5a8e975aaa6056554efe4c794d0
        with:
          body: ${{steps.github_release.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#       - name: Release
#         uses: softprops/action-gh-release@v1
#         with:
#           generate_release_notes: true
#           tag_name: v${{ env.REVISION }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
